name: SSL Status Update Automatically

on: 
  push:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Generate
        env:
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_KEY: ${{ secrets.CF_KEY }}
        run: |
          chmod +x ./cloudflare.sh
          chmod +x ./checker.sh
          ./cloudflare.sh
          cp ./index.html output/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.LAB_DEPLOY_KEY }}
          external_repository: Hans362-s-Lab/hans362-s-lab.github.io
          publish_branch: master
          publish_dir: ./output
          destination_dir: ssl
          force_orphan: false
