
name: SSL Status Update Automatically

on: 
  push:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-16.04
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Generate
        run: |
          chmod +x ./checker.sh
          ./checker.sh hans362.cn www.hans362.cn blog.hans362.cn friends.hans362.cn lab.hans362.cn static.hans362.cn storage.hans362.cn status.hans362.cn
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.LAB_DEPLOY_KEY }}
          external_repository: Hans362-s-Lab/hans362-s-lab.github.io
          publish_branch: master
          publish_dir: ./output
          destination_dir: ssl
          force_orphan: true