
name: SSL Status Update Automatically

on: 
  push:
  schedule: 
    - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Generate
        run: |
          chmod +x ./checker.sh
          ./checker.sh hans362.cn www.hans362.cn blog.hans362.cn friends.hans362.cn lab.hans362.cn static.hans362.cn storage.hans362.cn status.hans362.cn
          cp ./index.html output/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.LAB_DEPLOY_KEY }}
          external_repository: Hans362-s-Lab/hans362-s-lab.github.io
          publish_branch: master
          publish_dir: ./output
          destination_dir: ssl
          force_orphan: false
